[package]
name = "neko-main"
version = "0.1.0"
edition = "2024"

[dependencies]
neko-securities = { git = "https://github.com/FlorianRoudaut/neko-securities", branch = "main" }
neko-ibkr-api   = { git = "https://github.com/FlorianRoudaut/neko-ibkr-api",   branch = "main" }
uuid = { version = "1", features = ["v4", "serde"] }
prost = "0.13"

[patch."https://github.com/FlorianRoudaut/neko-securities"]
neko-securities = { path = "../neko-securities" }
